version: '3.7'

services:
  db:
    image: postgres:alpine
    ports:
     - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'user'
      POSTGRES_DB: 'postgres'
  local:
    build: 'Docker/'
    ports:
      - "8080"
      - "7600"
    depends_on:
      - db
    environment:
      DB_USERNAME: 'user'
      DB_CONNECTIONURL: 'jdbc:postgresql://db:5432/postgres'
      DB_PASSWORD: 'password'
      DISTRIBUTED_CACHE_OWNERS: '2'
      IS_LOCAL: 'true'
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - local
    ports:
      - "80:8080"